# Generated by Django 5.0.7 on 2025-01-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sold_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_car',
            name='img',
            field=models.ImageField(default=None, upload_to='media/'),
            preserve_default=False,
        ),
    ]
