# Generated by Django 5.0.7 on 2025-01-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sold_car_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_car',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
