# Generated by Django 5.0.7 on 2025-01-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sold_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_servise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('about', models.TextField()),
            ],
        ),
    ]
