# Generated by Django 5.0.7 on 2025-01-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_our_servise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Head_Office', models.CharField(max_length=37)),
                ('Branch_Office', models.CharField(max_length=37)),
                ('Customer_Service', models.EmailField(max_length=254)),
                ('Return_Refund', models.CharField(max_length=37)),
            ],
        ),
    ]
